version: '3.9'


services:
    flask-api:
        build: ./backend
        ports: 
            - 5000:5000

        depends_on:
            - postgres

    vue-app:
        build: ./frontend/vue_clinic_app
        ports: 
            - 8080:8080


    postgres:
        image: postgres:13
        environment:
            POSTGRES_DB: ${PG_DB}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:

